# -*- coding: utf-8 -*-
"""Task 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BF4CsX6IhFmWPauACioAOBNoCdiHSIT-

#Weather Advisor
"""

temperature = 18

if temperature >= 30:
    print("It's a hot day. Stay hydrated!")
elif 20 <= temperature <= 29:
    print("It's a warm day. Enjoy the weather!")
elif 10 <= temperature <= 19:
    print("It's a cool day. Wear a jacket!")
else:
    print("It's a cold day. Stay warm!")

"""#Filter and Transform a List"""

list = (range(1,21))

for i in range(len(list)) :
    if i % 3 == 0:
     print(i)